config/routes.rb
Rails.application.routes.draw do

  authenticated do
    root to: 'plans#index'
  end

  root to: 'home#index'

  resources :plans, path: :p do
    collection do
      put 'update_sort'
    end
    member do
      put 'update_task_sort'
    end
    resources :lists, only: [:new, :create, :update, :destroy] do
      collection do
        put 'update_sort'
      end
      resources :tasks, only: [:new, :create, :update, :destroy] do
        collection do
          put 'update_sort'
        end
      end
    end
    resources :tasks, only: [:create]
  end

  devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'signup',
  }, controllers: {
      registrations: :registrations,
  }

end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id         :integer          not null, primary key
#  title      :text(65535)
#  plan_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  color_tag  :integer          default(0)
#  user_id    :integer          not null
#

class List < ActiveRecord::Base

  has_many   :tasks, -> { order('status DESC, updated_at DESC') }, dependent: :destroy
  belongs_to :plan
  belongs_to :user
  has_one   :task_sort, class_name: 'Sort', as: :sortable, dependent: :destroy

  scope :with_color_tag, -> (color_tag) { where(color_tag: color_tag) }

  after_create :add_sort
  after_destroy :delete_sort

  def add_sort
    list_sort = plan.list_sort
    if list_sort.nil?
      list_sort = plan.build_list_sort
      list_sort.sort = plan.lists.pluck(:id)
    else
      list_sort.sort.push(id)
    end
    list_sort.save
  end

  def delete_sort
    list_sort = plan.list_sort
    if list_sort.present?
      list_sort.sort.delete(id)
      list_sort.save
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plan, only: [:new, :create, :update_sort, :update]
  before_action :set_list, only: [:update, :destroy]

  # GET /lists/new
  def new
    @list = @plan.lists.new
  end

  # POST /lists.json
  def create
    @list = @plan.lists.new(list_params)
    @list.user_id = current_user.id

    unless @list.save
      render json: {status: 'failed', message: '创建失败，请稍后重试 !'}
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    unless @list.update(list_params)
      render json: {status: 'failed', message: '更新失败，请稍后重试 !'}
    end
  end

  # PATCH/PUT /p/update_sort.json
  def update_sort
    list_sort = @plan.list_sort
    list_sort = @plan.build_list_sort if list_sort.nil?
    list_sort.sort = params[:sort].split(',').map(&:to_i)
    unless list_sort.save
      render json: {status: 'failed', message: '更新失败，请稍后重试 !'}
    end
  end

  # DELETE /lists/1.json
  def destroy
    @list.destroy
    render json: {status: 'success', message: '删除列表成功!'}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = current_user.plans.find_by_ident(params[:plan_id])
      unless @plan
        respond_to do |format|
          format.html { redirect_to root_url, alert: '此计划不存在' }
          format.json { render json: {alert: '此计划不存在'} }
        end
      end
    end

    def set_list
      @list = current_user.lists.find(params[:id])
      unless @list
        respond_to do |format|
          format.html { redirect_to root_url, alert: '此列表不存在' }
          format.json { render json: {alert: '此列表不存在'} }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :color_tag)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_edit_form.html.haml
.form.form-horizontal.plan#edit_list
  .field
    = text_field_tag :list_title, nil, class: 'form-control', required: true, placeholder: '名称',
                     'v-model' => 'list.title'
  .field
    .color-select-feild
      = collection_radio_buttons :edit_list_color_tag, nil, options_for_color, :last, :first do |b|
        = b.radio_button({class: 'color-radio selected-radio', 'v-model' => 'list.color_tag'})
        = label_tag '', '', style: "background-color: #{b.text}", 'v-on:click' => "selectColor('#{b.text}', 'edit')", value: b.value
      .edit-list-buttons
        %a.cancel{'v-on:click' => 'cancelEditList()'} 取消
        %a.update{'v-on:click' => 'submitEditList(list.id)'} 更新

app/views/lists/_form.html.haml
.form.form-horizontal.plan#new_list
  .field
    = text_field_tag :list_title, nil, class: 'form-control', required: true, placeholder: '名称',
                     'v-model' => 'list.title', 'v-on:keyup.enter' => 'addList'
  .field
    .color-select-feild
      = collection_radio_buttons :list_color_tag, nil, options_for_color, :last, :first do |b|
        = b.radio_button({class: 'color-radio selected-radio', 'v-model' => 'list.color_tag'})
        = label_tag "list_color_tag__#{b.value}", '', style: "background-color: #{b.text}", 'v-on:click' => "selectColor('#{b.text}', 'new')"

app/views/lists/edit.html.haml
%h1 Editing List
= render 'form'
= link_to 'Show', @list
|
= link_to 'Back', lists_path

app/views/lists/index.html.haml
%p#notice= notice
%h1 Listing Lists
%table
  %thead
    %tr
      %th Title
      %th Plan
      %th{:colspan => "3"}
  %tbody
    - @lists.each do |list|
      %tr
        %td= list.title
        %td= list.plan_id
        %td= link_to 'Show', list
        %td= link_to 'Edit', edit_list_path(list)
        %td= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New List', new_list_path

app/views/lists/new.html.haml
- title '新建任务组'
%h4 新建任务组
= render 'form'

app/views/lists/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @list.title
%p
  %strong Plan:
  = @list.plan_id
= link_to 'Edit', edit_list_path(@list)
|
= link_to 'Back', lists_path