config/routes.rb
Rails.application.routes.draw do

  authenticated do
    root to: 'plans#index'
  end

  root to: 'home#index'

  resources :plans, path: :p do
    collection do
      put 'update_sort'
    end
    member do
      put 'update_task_sort'
    end
    resources :lists, only: [:new, :create, :update, :destroy] do
      collection do
        put 'update_sort'
      end
      resources :tasks, only: [:new, :create, :update, :destroy] do
        collection do
          put 'update_sort'
        end
      end
    end
    resources :tasks, only: [:create]
  end

  devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'signup',
  }, controllers: {
      registrations: :registrations,
  }

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  title       :text(65535)
#  description :text(65535)
#  status      :integer          default(1)
#  list_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  plan_id     :integer
#  user_id     :integer          not null
#

class Task < ActiveRecord::Base

  belongs_to :plan
  belongs_to :list
  belongs_to :user

  after_create :add_sort
  after_destroy :delete_sort


  def closed?
    self.status == 0
  end

  def opened?
    self.status == 1
  end

  def add_sort
    task_sort = list.task_sort
    if task_sort.nil?
      task_sort = list.build_task_sort
      task_sort.sort = list.tasks.pluck(:id)
    else
      task_sort.sort.unshift(id)
    end
    task_sort.save
  end

  def delete_sort
    task_sort = list.task_sort
    if task_sort.present?
      task_sort.sort.delete(id)
      task_sort.save
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plan_list, only: [:new, :create, :update, :update_sort]
  before_action :set_task, only: [:update, :destroy]

  # GET /tasks/new
  def new
    @task = @list.tasks.new
  end

  # POST /tasks.json
  def create
    @task = @plan.tasks.new(task_params)
    @task.list = @list
    @task.user_id = current_user.id

    unless @task.save
      render json: {status: 'failed', message: '创建失败，请稍后重试 !'}
    end
  end

  # PATCH/PUT /tasks/1.json
  def update
    unless @task.update(task_params)
      render json: {status: 'failed', message: '任务更新失败, 请稍后重试 !'}
    end
  end

  # PATCH/PUT /tasks/update_sort.json
  def update_sort
    list_sort = @list.task_sort
    list_sort = @list.build_task_sort if list_sort.nil?
    list_sort.sort = params[:sort].split(',').map(&:to_i)
    unless list_sort.save
      render json: {status: 'failed', message: '更新失败，请稍后重试 !'}
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: '任务已被删除!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan_list
      @plan = current_user.plans.find_by_ident(params[:plan_id])
      @list = current_user.lists.find_by_id(params[:list_id])
      unless @plan && @list
        respond_to do |format|
          format.html { redirect_to root_url, alert: '此计划或列表不存在' }
          format.json { render json: {alert: '此计划或列表不存在'} }
        end
      end
    end

    def set_task
      @task = current_user.tasks.find(params[:id])
      unless @task
        respond_to do |format|
          format.html { redirect_to root_url, alert: '此任务不存在' }
          format.json { render json: {alert: '此任务不存在'} }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :status)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
- new_form = type == 'new' ? true : false
.form.form-horizontal.plan{id: new_form ? 'new_task' : 'edit_task'}
  .field
    = text_field_tag :task_title, nil, class: 'form-control', required: true, placeholder: '任务名称',
                     'v-on:keypress.enter' => new_form ? 'addTask' : "updateTask('edit')"
    = hidden_field_tag :new_task_path, nil, 'v-model' => 'list.path'
  %span.enter-notice
    可按回车(Enter)提交
  .field.add-task-buttons
    %button.btn.btn-sm.btn-default{ :type => "button", 'v-on:click' => new_form ? 'cancelTask' : 'removeEdit' } 取消
    %button.btn.btn-sm.btn-primary{ :type => "button", 'v-on:click' => new_form ? 'addTask' : "updateTask('edit')" }
      = new_form ? '提交' : '更新'

app/views/tasks/edit.html.haml
- model_class = Task
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/tasks/index.html.haml
- model_class = Task
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:status)
      %th= model_class.human_attribute_name(:list_id)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @tasks.each do |task|
      %tr
        %td= link_to task.id, task_path(task)
        %td= task.title
        %td= task.description
        %td= task.status
        %td= task.list_id
        %td= l task.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")),
            edit_task_path(task), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")),
            task_path(task),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-xs btn-danger'
= link_to t('.new', :default => t("helpers.links.new")),
  new_task_path,
  :class => 'btn btn-primary'

app/views/tasks/new.html.haml
- title '新建任务'
.page-header
  %h4 新建任务
= render 'form'

app/views/tasks/show.html.haml
- model_class = Task
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:title)
      \:
  %dd= @task.title
  %dt
    %strong
      = model_class.human_attribute_name(:description)
      \:
  %dd= @task.description
  %dt
    %strong
      = model_class.human_attribute_name(:status)
      \:
  %dd= @task.status
= link_to t('.back', :default => t("helpers.links.back")),
  tasks_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")),
  edit_task_path(@task), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")),
  task_path(@task),
  :method => 'delete',
  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
  :class => 'btn btn-danger'