config/routes.rb
Rails.application.routes.draw do

  authenticated do
    root to: 'plans#index'
  end

  root to: 'home#index'

  resources :plans, path: :p do
    collection do
      put 'update_sort'
    end
    member do
      put 'update_task_sort'
    end
    resources :lists, only: [:new, :create, :update, :destroy] do
      collection do
        put 'update_sort'
      end
      resources :tasks, only: [:new, :create, :update, :destroy] do
        collection do
          put 'update_sort'
        end
      end
    end
    resources :tasks, only: [:create]
  end

  devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'signup',
  }, controllers: {
      registrations: :registrations,
  }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout 'index', only: [:index]

  def index
  end

  private

  # show devise form in index page
  # refer: https://pupeno.com/2016/04/26/show-a-devise-log-in-or-sign-up-forms-in-another-page/
  def resource_name
    :user
  end
  helper_method :resource_name

  def resource
    @resource ||= User.new
  end
  helper_method :resource

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  helper_method :devise_mapping

  def resource_class
    User
  end
  helper_method :resource_class

end

app/views/home/index.html.haml
%header#page-header
  .container
    .row
      .col-md-8.index-des
        %p.des-title
          Taskover
        %p.short-des
          开源个人任务管理工具
        %p.full-des
          Taskover 是一款开源个人任务管理工具，通过简单易用的任务归纳分类方式
        %p.full-des
          用来帮助您高效的追踪管理各项任务，最大化的提升工作效率
        %p.demo-des
          演示地址：
          = link_to '点击试用', 'http://115.28.75.212/'
        %p.demo-des
          演示账号： demo / 111111
      .col-md-4.index-reg
        .reg-from
          = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'form-horizontal' }) do |f|
            = devise_error_messages!
            .form-group
              = f.text_field :ident, placeholder: '用户名: 支持大小写英文字母及数字', autofocus: true, class: 'form-control'
            .form-group
              = f.email_field :email, placeholder: '邮箱: 请输入您的邮箱', class: 'form-control'
            .form-group
              = f.password_field :password, placeholder: '密码: 密码不少于6位', class: 'form-control'
            .form-group
              = f.password_field :password_confirmation, placeholder: '确认密码: 再次输入密码', class: 'form-control'
            .form-group
              = f.submit '注册 Taskover 账户', class: 'btn btn-primary reg-btn-index'
            %p.terms-link
              点击注册按钮之后，即代表您同意并遵守
              = link_to '使用条款', user_session_path
            %p.account-link
              已经注册？点击
              = link_to '登录', user_session_path
.demo-first
  .container
    .row
      .col-md-12.demo-pic
        %h3
          简易方便的任务分类（Plan）
        = image_tag '/files/taskover1.gif', class: 'thumbnail'
.demo-second
  .container
    .row
      .col-md-12.demo-pic
        %h3
          简单易用的任务分组（List）
        = image_tag '/files/taskover2.gif', class: 'thumbnail'
.demo-third
  .container
    .row
      .col-md-12.demo-pic
        %h3
          简单高效的任务管理（Task）
        = image_tag '/files/taskover3.gif', class: 'thumbnail'
.home-footer
  .container
    .row
      .col-md-12
        .link-item
          = link_to '源代码 Host on Gitee', 'https://gitee.com/kesin/taskover'
          = link_to '建议反馈', 'https://zoker.io/taskover'